import type { ProductSnapshot } from "./wallet-product";

// Synthetic product fixtures; no destination addresses or customer account data.
export const MULTI_ACCOUNT_DEMO = {
  fiatCurrency: "USD",
  accounts: [
    {
      id: "demo-custody",
      kind: "custodial",
      label: "Основной",
      status: "active",
      capabilities: [
        // Local commerce fixtures grant only this exact placement; no provider is connected.
        {
          action: "buy",
          assetId: "usdc",
          symbol: "USDC",
          name: "USD Coin",
          networkId: "ethereum",
          networkLabel: "Ethereum",
        },
        {
          action: "swap",
          assetId: "usdc",
          symbol: "USDC",
          name: "USD Coin",
          networkId: "ethereum",
          networkLabel: "Ethereum",
        },
        {
          action: "send",
          assetId: "btc",
          symbol: "BTC",
          name: "Bitcoin",
          networkId: "bitcoin",
          networkLabel: "Bitcoin",
        },
        {
          action: "send",
          assetId: "eth",
          symbol: "ETH",
          name: "Ethereum",
          networkId: "ethereum",
          networkLabel: "Ethereum",
        },
        {
          action: "send",
          assetId: "usdc",
          symbol: "USDC",
          name: "USD Coin",
          networkId: "ethereum",
          networkLabel: "Ethereum",
        },
        {
          action: "send",
          assetId: "usdc",
          symbol: "USDC",
          name: "USD Coin",
          networkId: "solana",
          networkLabel: "Solana",
        },
        {
          action: "receive",
          receiveMode: "external-address",
          assetId: "btc",
          symbol: "BTC",
          name: "Bitcoin",
          networkId: "bitcoin",
          networkLabel: "Bitcoin",
        },
        {
          action: "receive",
          receiveMode: "external-address",
          assetId: "eth",
          symbol: "ETH",
          name: "Ethereum",
          networkId: "ethereum",
          networkLabel: "Ethereum",
        },
        {
          action: "receive",
          receiveMode: "external-address",
          assetId: "usdc",
          symbol: "USDC",
          name: "USD Coin",
          networkId: "ethereum",
          networkLabel: "Ethereum",
        },
        {
          action: "receive",
          receiveMode: "external-address",
          assetId: "usdc",
          symbol: "USDC",
          name: "USD Coin",
          networkId: "solana",
          networkLabel: "Solana",
        },
      ],
    },
    {
      id: "demo-depositary",
      kind: "depositary",
      label: "Хранилище",
      status: "active",
      capabilities: [
        {
          action: "receive",
          receiveMode: "internal-transfer",
          assetId: "usdc",
          symbol: "USDC",
          name: "USD Coin",
          networkId: "ethereum",
          networkLabel: "Ethereum",
        },
        {
          action: "receive",
          receiveMode: "unavailable",
          assetId: "usdc",
          symbol: "USDC",
          name: "USD Coin",
          networkId: "solana",
          networkLabel: "Solana",
        },
      ],
    },
    {
      id: "demo-inactive",
      kind: "depositary",
      label: "Размещение",
      status: "inactive",
      capabilities: [
        {
          action: "receive",
          receiveMode: "internal-transfer",
          assetId: "usdc",
          symbol: "USDC",
          name: "USD Coin",
          networkId: "ethereum",
          networkLabel: "Ethereum",
        },
      ],
    },
    {
      id: "demo-private",
      kind: "private",
      label: "Приватный",
      status: "unavailable",
      capabilities: [
        {
          action: "receive",
          receiveMode: "external-address",
          assetId: "usdc",
          symbol: "USDC",
          name: "USD Coin",
          networkId: "ethereum",
          networkLabel: "Ethereum",
        },
      ],
    },
  ],
  holdings: [
    {
      id: "demo-btc",
      accountId: "demo-custody",
      assetId: "btc",
      symbol: "BTC",
      name: "Bitcoin",
      networkId: "bitcoin",
      networkLabel: "Bitcoin",
      quantity: "0.12",
      fiatMinor: 804_025,
      availableQuantity: "0.12",
    },
    {
      id: "demo-eth",
      accountId: "demo-custody",
      assetId: "eth",
      symbol: "ETH",
      name: "Ethereum",
      networkId: "ethereum",
      networkLabel: "Ethereum",
      quantity: "1.1",
      fiatMinor: 390_050,
    },
    {
      id: "demo-usdc-eth",
      accountId: "demo-custody",
      assetId: "usdc",
      symbol: "USDC",
      name: "USD Coin",
      networkId: "ethereum",
      networkLabel: "Ethereum",
      quantity: "500",
      fiatMinor: 50_000,
      availableQuantity: "500",
    },
    {
      id: "demo-usdc-sol",
      accountId: "demo-custody",
      assetId: "usdc",
      symbol: "USDC",
      name: "USD Coin",
      networkId: "solana",
      networkLabel: "Solana",
      quantity: "400",
      fiatMinor: 40_000,
      availableQuantity: "400",
    },
    {
      id: "demo-inactive-usdc",
      accountId: "demo-inactive",
      assetId: "usdc",
      symbol: "USDC",
      name: "USD Coin",
      networkId: "ethereum",
      networkLabel: "Ethereum",
      quantity: "0",
      fiatMinor: 0,
      availableQuantity: "0",
    },
  ],
  batteryPools: [
    {
      id: "demo-ethereum-transfer-pool",
      networkId: "ethereum",
      networkLabel: "Ethereum",
      eligibleAccountIds: ["demo-custody", "demo-depositary"],
      action: "send",
      remainingTransfers: 3,
    },
  ],
} as const satisfies ProductSnapshot;

export const SINGLE_ACCOUNT_DEMO = {
  fiatCurrency: "USD",
  accounts: [
    {
      id: "demo-single",
      kind: "custodial",
      label: "Основной",
      status: "active",
      capabilities: [
        {
          action: "send",
          assetId: "usdc",
          symbol: "USDC",
          name: "USD Coin",
          networkId: "ethereum",
          networkLabel: "Ethereum",
        },
        {
          action: "receive",
          receiveMode: "external-address",
          assetId: "usdc",
          symbol: "USDC",
          name: "USD Coin",
          networkId: "ethereum",
          networkLabel: "Ethereum",
        },
      ],
    },
  ],
  holdings: [
    {
      id: "demo-single-usdc",
      accountId: "demo-single",
      assetId: "usdc",
      symbol: "USDC",
      name: "USD Coin",
      networkId: "ethereum",
      networkLabel: "Ethereum",
      quantity: "1250",
      fiatMinor: 125_000,
      availableQuantity: "1250",
    },
  ],
  batteryPools: [],
} as const satisfies ProductSnapshot;
